BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS age_group VARCHAR(20),
    ADD COLUMN IF NOT EXISTS activity_level VARCHAR(50),
    ADD COLUMN IF NOT EXISTS outdoor_exposure VARCHAR(30),
    ADD COLUMN IF NOT EXISTS notification_enabled BOOLEAN NOT NULL DEFAULT TRUE;

COMMIT;
